### ISSUE TITLE
Provide stable tags

### ISSUE THREAD

**Issue by olivierdalang** [andriyreznik/docker-python-gdal#10]
Hi !

Nice image which does what is advertised ! Thanks.

It would be nice to provide stable tags (that do not change over time) such as (for the current Dockerfile) :
- `py3.7.3-gdal3.0.0`

Currently, the `stable` tag will likely change when GDAL or python version is bumped.

Thanks,

Olivier

**Comment by andrejreznik** [comment]
Hello, Olivier!

Thx for your interest.
I really wanted to do it at least when I updated GDAL to 3.0.0

So, what about to keep Dockerfiles with different versions of Python and
GDAL and separate directories? Or branches would be preferred?

**Comment by andrejreznik** [comment]
Hello, Olivier!
Thx for your interest.
I really wanted to do it at least when I updated GDAL to 3.0.0
So, now I decide what would be preferred to keep Dockerfiles with different versions of Python and GDAL in separate directories or use different branches.

**Comment by olivierdalang** [comment]
I'd use branches for versions (as in the long term there may be plenty of them)
